### Generics for ppstat. 

setGeneric("anticipating", function(model, ...) standardGeneric("anticipating"))
setGeneric("coefficients<-", function(model, value) standardGeneric("coefficients<-"))
setGeneric("computeLinearPredictor", function(model, ...) standardGeneric("computeLinearPredictor"))
setGeneric("computeBasis", function(model, ...) standardGeneric("computeBasis"))
setGeneric("computeLoss", function(model, ...) standardGeneric("computeLoss"))
setGeneric("computeQuadraticContrast", function(model, coefficients = NULL, ...) standardGeneric("computeQuadraticContrast"))
setGeneric("computeMinusLogLikelihood", function(model, coefficients = NULL, ...) standardGeneric("computeMinusLogLikelihood"))
setGeneric("computeDMinusLogLikelihood", function(model, coefficients = NULL, ...) standardGeneric("computeDMinusLogLikelihood"))
setGeneric("computeDDMinusLogLikelihood", function(model, coefficients = NULL, ...) standardGeneric("computeDDMinusLogLikelihood"))
setGeneric("computeFisherInformation", function(model, coefficients = NULL, ...) standardGeneric("computeFisherInformation"))
setGeneric("computeModelMatrix", function(model, evaluationPositions = NULL, ...) standardGeneric("computeModelMatrix"))
setGeneric("computeRecurrenceMatrix", function(model, evaluationPositions = NULL, A = 1000, ...) standardGeneric("computeRecurrenceMatrix"))
setGeneric("computeSandwichKJ", function(model, ...) standardGeneric("computeSandwichKJ"))
setGeneric("computeWeights", function(model, coefficients = NULL, ...) standardGeneric("computeWeights"))
setGeneric("computeWorkingResponse", function(model, coefficients = NULL, ...) standardGeneric("computeWorkingResponse"))
setGeneric("computeVar", function(model, ...) standardGeneric("computeVar"))
setGeneric("formula<-", function(model, value) standardGeneric("formula<-"))
setGeneric("getAssign", function(model, ...) standardGeneric("getAssign"))
setGeneric("getAdjacencyMatrix", function(model, ...) standardGeneric("getAdjacencyMatrix"))
setGeneric("getBasis", function(model, term, ...) standardGeneric("getBasis"))
setGeneric("getCrossProd", function(model, term, ...) standardGeneric("getCrossProd"))
setGeneric("getInformation", function(model, ...) standardGeneric("getInformation"))
setGeneric("getTermPlotData", function(model, ...) standardGeneric("getTermPlotData"))
setGeneric("getFilterTerms", function(model, ...) standardGeneric("getFilterTerms"))
setGeneric("getLinearFilter", function(model, ...) standardGeneric("getLinearFilter"))
setGeneric("getModels", function(model, ...) standardGeneric("getModels"))
setGeneric("getModelMatrix", function(model, col,...) standardGeneric("getModelMatrix"))
setGeneric("getKernelAssign", function(model, ...) standardGeneric("getKernelAssign"))
setGeneric("getKernelBasis", function(model, ...) standardGeneric("getKernelBasis"))
setGeneric("getKernelMatrix", function(model, col,...) standardGeneric("getKernelMatrix"))
setGeneric("getKernelTerms", function(model, ...) standardGeneric("getKernelTerms"))
setGeneric("getModelMatrixEnv", function(model, ...) standardGeneric("getModelMatrixEnv"))
setGeneric("getResponseKernelMatrix", function(model,...) standardGeneric("getResponseKernelMatrix"))
setGeneric("getResponseMatrix", function(model,...) standardGeneric("getResponseMatrix"))
setGeneric("getSmoothTerms", function(model, ...) standardGeneric("getSmoothTerms"))
setGeneric("getz", function(model, col,...) standardGeneric("getz"))
setGeneric("getV", function(model, ...) standardGeneric("getV"))
setGeneric("kernelCoefficients", function(object, ...) standardGeneric("kernelCoefficients"))
setGeneric("iwlsFit", function(model, ...) standardGeneric("iwlsFit"))
setGeneric("processData", function(model, ...) standardGeneric("processData"))
setGeneric("ppmFit", function(model, ...) standardGeneric("ppmFit"))
setGeneric("optimFit", function(model, ...) standardGeneric("optimFit"))
setGeneric("glmFit", function(model, ...) standardGeneric("glmFit"))
setGeneric("glmnetFit", function(model, ...) standardGeneric("glmnetFit"))
setGeneric("grpLassoFit", function(model, ...) standardGeneric("grpLassoFit"))
setGeneric("lsFit", function(model, ...) standardGeneric("lsFit"))
setGeneric("penalty", function(model, ...) standardGeneric("penalty"))
setGeneric("penalty<-", function(model, value) standardGeneric("penalty<-"))
setGeneric("response", function(model, ...) standardGeneric("response"))
setGeneric("setBasis<-", function(model, term, value) standardGeneric("setBasis<-"))
setGeneric("setModels<-", function(model, value) standardGeneric("setModels<-"))
setGeneric("setFilterTerms<-", function(model, value) standardGeneric("setFilterTerms<-"))
setGeneric("setModelMatrixEnv<-", function(model, value) standardGeneric("setModelMatrixEnv<-"))
setGeneric("stepInformation", function(model, ...) standardGeneric("stepInformation"))
setGeneric("processData<-", function(model, value) standardGeneric("processData<-"))
setGeneric("termPlot", function(model, ...) standardGeneric("termPlot"))
setGeneric("updateCrossProd", function(model, ...) standardGeneric("updateCrossProd"))
setGeneric("updateKernelMatrix", function(model, ...) standardGeneric("updateKernelMatrix"))
setGeneric("updateModelMatrix", function(model, ...) standardGeneric("updateModelMatrix"))
setGeneric("updateResponseKernelMatrix", function(model, ...) standardGeneric("updateResponseKernelMatrix"))
setGeneric("updateResponseMatrix", function(model, ...) standardGeneric("updateResponseMatrix"))
