### Generics for package processdata.
setGeneric("continuousProcess", function(continuousData, ...) standardGeneric("continuousProcess"))
setGeneric("colNames", function(object, type, ...) standardGeneric("colNames"))
setGeneric("getColumns", function(object, j, ...) standardGeneric("getColumns"))
setGeneric("getEquiDistance", function(object, ...) standardGeneric("getEquiDistance"))
setGeneric("getId", function(object, ...) standardGeneric("getId"))
setGeneric("getNumerics", function(object, ...) standardGeneric("getNumerics"))
setGeneric("getFactors", function(object, ...) standardGeneric("getFactors"))
setGeneric("getUnitData", function(object, ...) standardGeneric("getUnitData"))
setGeneric("getMarkType", function(object, ...) standardGeneric("getMarkType"))
setGeneric("getType", function(object, ...) standardGeneric("getType"))
setGeneric("getPointId", function(object, ...) standardGeneric("getPointId"))
setGeneric("getPointPosition", function(object, ...) standardGeneric("getPointPosition"))
setGeneric("getPointTime", function(object, ...) standardGeneric("getPointTime"))
setGeneric("getMarkValue", function(object, ...) standardGeneric("getMarkValue"))
setGeneric("getPlotData", function(object, ...) standardGeneric("getPlotData"))
setGeneric("getPointPosition", function(object, ...) standardGeneric("getPointPosition"))
setGeneric("getPointPointer",function(object, mark, ...) standardGeneric("getPointPointer"))
setGeneric("getPosition",function(object, ...) standardGeneric("getPosition"))
setGeneric("getTime",function(object, ...) standardGeneric("getTime"))
setGeneric("getValue",function(object, ...) standardGeneric("getValue"))
setGeneric("integrator", function(object, ...) standardGeneric("integrator"))
setGeneric("iSubset",function(object, ...) standardGeneric("iSubset"))
setGeneric("iSubset<-",function(object, value) standardGeneric("iSubset<-"))
setGeneric("jSubset",function(object, ...) standardGeneric("jSubset"))
setGeneric("jSubset<-",function(object, value) standardGeneric("jSubset<-"))
setGeneric("iUnitSubset",function(object, ...) standardGeneric("iUnitSubset"))
setGeneric("iUnitSubset<-",function(object, value) standardGeneric("iUnitSubset<-"))
setGeneric("jUnitSubset",function(object, ...) standardGeneric("jUnitSubset"))
setGeneric("jUnitSubset<-",function(object, value) standardGeneric("jUnitSubset<-"))
setGeneric("iPointSubset",function(object, ...) standardGeneric("iPointSubset"))
setGeneric("iPointSubset<-",function(object, value) standardGeneric("iPointSubset<-"))
setGeneric("jPointSubset", function(object, ...) standardGeneric("jPointSubset"))
setGeneric("jPointSubset<-", function(object, value) standardGeneric("jPointSubset<-"))
setGeneric("jumpProcess", function (object, ...) standardGeneric("jumpProcess"))
setGeneric("markedPointProcess", function(pointData, continuousData, ...) standardGeneric("markedPointProcess"))
setGeneric("process", function(unitData, ...) standardGeneric("process"))
setGeneric("setUnitData<-", function(object, value) standardGeneric("setUnitData<-"))
setGeneric("setPointPointer<-", function(object, value) standardGeneric("setPointPointer<-"))
setGeneric("summarizeData", function(object, ...) standardGeneric("summarizeData"))
setGeneric("simpleSummary", function(object, ...) standardGeneric("simpleSummary"))
setGeneric("unsubset", function(x, ...) standardGeneric("unsubset"))
setGeneric("updateProcessObject", function(object, ...) standardGeneric("updateProcessObject"))
